use_frameworks!

platform :ios, '10.0'

target 'YKSwiftNetworking_Example' do
  pod 'YKSwiftNetworking', :path => '../'

  target 'YKSwiftNetworking_Tests' do
    inherit! :search_paths

    
  end
end
