use_frameworks!

platform :ios, '9.0'

target 'YKSwiftCommandModule_Example' do
  pod 'YKSwiftCommandModule', :path => '../'

  target 'YKSwiftCommandModule_Tests' do
    inherit! :search_paths

    
  end
end
