use_frameworks!

platform :ios, '10.0'

target 'YKNetWorking_Example' do
  pod 'YKNetWorking', :path => '../'
  pod 'YKNetWorking/RAC', :path => '../'

  target 'YKNetWorking_Tests' do
    inherit! :search_paths

    
  end
end
