use_frameworks!

platform :ios, '10.0'

target 'YKSwiftSectionViewModel_Example' do
  pod 'YKSwiftSectionViewModel', :path => '../'

  target 'YKSwiftSectionViewModel_Tests' do
    inherit! :search_paths

    
  end
end
